version: '3.4'

services:
  redis:
    image: redis:5.0.7
    container_name: redis
    command: ['--requirepass redis_password', '--notify-keyspace-events KEA']
    ports:
      - 6379:6379

  biostasis_database:
    env_file:
      - .env
    image: mysql:8.0.20
    container_name: biostasis_database
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: Europe/London
    entrypoint: sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS biostasis_test;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password"
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-authentication-plugin=mysql_native_password',
      ]
